package Ventanas;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Desktop-PC
 */
public class RegistroPaciente extends javax.swing.JFrame {

    public RegistroPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabelTituloPaciente = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelFechNacimiento = new javax.swing.JLabel();
        jLabelDirec = new javax.swing.JLabel();
        jLabelProvin = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jtf_ced = new javax.swing.JTextField();
        jtf_nom = new javax.swing.JTextField();
        jtf_sex = new javax.swing.JTextField();
        jtf_fec = new javax.swing.JTextField();
        jtf_dir = new javax.swing.JTextField();
        jtf_pro = new javax.swing.JTextField();
        jButtonRegresar = new javax.swing.JButton();
        jb_mod = new javax.swing.JButton();
        jb_reg = new javax.swing.JButton();
        jb_eli = new javax.swing.JButton();
        jtf_tel = new javax.swing.JTextField();
        jtf_bus = new javax.swing.JTextField();
        jLabelCedula1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jTextField4.setText("jTextField4");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));

        jLabelTituloPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelTituloPaciente.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTituloPaciente.setText("Registrar Paciente");

        jLabelCedula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(153, 153, 153));
        jLabelCedula.setText("Cedula :");

        jLabelNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(153, 153, 153));
        jLabelNombre.setText("Nombre :");

        jLabelSexo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelSexo.setText("Sexo :");

        jLabelFechNacimiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelFechNacimiento.setForeground(new java.awt.Color(153, 153, 153));
        jLabelFechNacimiento.setText("Fecha de Nacimiento :");

        jLabelDirec.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelDirec.setForeground(new java.awt.Color(153, 153, 153));
        jLabelDirec.setText("Direccion :");

        jLabelProvin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelProvin.setForeground(new java.awt.Color(153, 153, 153));
        jLabelProvin.setText("Provincia :");

        jLabelTelefono.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTelefono.setText("Telefono :");

        jtf_ced.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtf_nom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtf_sex.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtf_fec.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_fec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_fecActionPerformed(evt);
            }
        });

        jtf_dir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dirActionPerformed(evt);
            }
        });

        jtf_pro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_proActionPerformed(evt);
            }
        });

        jButtonRegresar.setBackground(new java.awt.Color(102, 33, 58));
        jButtonRegresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jb_mod.setBackground(new java.awt.Color(38, 36, 87));
        jb_mod.setForeground(new java.awt.Color(255, 255, 255));
        jb_mod.setText("Modificar");
        jb_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modActionPerformed(evt);
            }
        });

        jb_reg.setBackground(new java.awt.Color(38, 36, 87));
        jb_reg.setForeground(new java.awt.Color(255, 255, 255));
        jb_reg.setText("Registrar");
        jb_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regActionPerformed(evt);
            }
        });

        jb_eli.setBackground(new java.awt.Color(38, 36, 87));
        jb_eli.setForeground(new java.awt.Color(255, 255, 255));
        jb_eli.setText("Eliminar");
        jb_eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliActionPerformed(evt);
            }
        });

        jtf_tel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telActionPerformed(evt);
            }
        });

        jtf_bus.setToolTipText("Escriba el ID del Paciente");
        jtf_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_busActionPerformed(evt);
            }
        });

        jLabelCedula1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCedula1.setForeground(new java.awt.Color(153, 153, 153));
        jLabelCedula1.setText("Cedula :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTituloPaciente)
                                .addGap(119, 119, 119)
                                .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCedula)
                                .addGap(5, 5, 5)
                                .addComponent(jtf_ced, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addGap(5, 5, 5)
                                .addComponent(jtf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSexo)
                                .addGap(5, 5, 5)
                                .addComponent(jtf_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFechNacimiento)
                                .addGap(5, 5, 5)
                                .addComponent(jtf_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDirec)
                                .addGap(5, 5, 5)
                                .addComponent(jtf_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProvin)
                                .addGap(5, 5, 5)
                                .addComponent(jtf_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTelefono)
                                .addGap(5, 5, 5)
                                .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jb_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jb_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCedula1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloPaciente)
                    .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCedula)
                    .addComponent(jtf_ced, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNombre))
                    .addComponent(jtf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelSexo))
                    .addComponent(jtf_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelFechNacimiento))
                    .addComponent(jtf_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelDirec))
                    .addComponent(jtf_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelProvin))
                    .addComponent(jtf_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelTelefono))
                    .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCedula1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dirActionPerformed

    private void jb_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modActionPerformed
        String bus = jtf_bus.getText();
        if (bus.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese cedula del paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            File nuevoPaciente = new File("Hospital\\Pacientes\\" + bus + ".txt");
            if (nuevoPaciente.exists()) {
                // Asignación de texto al boton registrar->guardar y la casilla de busqueda de cedula a vacio
                jb_reg.setText("Guardar");
                jtf_bus.setText("");
                // Bloqueo de casiilas y botones
                jb_mod.setEnabled(false);
                jb_eli.setEnabled(false);
                jtf_bus.setEnabled(false);
                jtf_ced.setEnabled(false);

                BufferedReader reader;
                try {
                    reader = new BufferedReader(new FileReader("Hospital\\Pacientes\\" + bus + ".txt"));
                    String line = reader.readLine();
                    int numLinea = 1;
                    while (line != null) {
                        if (numLinea == 1) {
                            jtf_ced.setText(line);
                        } else if (numLinea == 2) {
                            jtf_nom.setText(line);
                        } else if (numLinea == 3) {
                            jtf_sex.setText(line);
                        } else if (numLinea == 4) {
                            jtf_fec.setText(line);
                        } else if (numLinea == 5) {
                            jtf_dir.setText(line);
                        } else if (numLinea == 6) {
                            jtf_pro.setText(line);
                        } else if (numLinea == 7) {
                            jtf_tel.setText(line);
                        } else {
                            break;
                        }
                        line = reader.readLine();
                        numLinea++;
                    }
                    reader.close();
                } catch (IOException e) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "Paciente " + bus + " inexistente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        jtf_bus.setText("");
    }//GEN-LAST:event_jb_modActionPerformed

    private void jb_eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliActionPerformed
        String bus = jtf_bus.getText();
        if (bus.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese cedula del paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            File file = new File("Hospital\\Pacientes\\" + bus + ".txt");
            if (file.delete()) {
                JOptionPane.showMessageDialog(null, "Paciente eliminado exitosamente", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Paciente " + bus + " inexistente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        jtf_bus.setText("");
    }//GEN-LAST:event_jb_eliActionPerformed

    private void jb_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regActionPerformed
        String ced = jtf_ced.getText();
        String nom = jtf_nom.getText();
        String sex = jtf_sex.getText();
        String fec = jtf_fec.getText();
        String dir = jtf_dir.getText();
        String pro = jtf_pro.getText();
        String tel = jtf_tel.getText();

        if (ced.isEmpty() || nom.isEmpty() || sex.isEmpty() || fec.isEmpty() || dir.isEmpty() || pro.isEmpty() || tel.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los espacios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            jb_mod.setEnabled(true);
            jb_eli.setEnabled(true);
            jtf_bus.setEnabled(true);
            jtf_ced.setEnabled(true);
            if (jb_reg.getText().equals("Registrar")) {
                File nuevoPaciente = new File("Hospital\\Pacientes\\" + ced + ".txt");
                if (nuevoPaciente.exists()) {
                    JOptionPane.showMessageDialog(null, "Paciente ya registrado", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
                } else {
                    try {
                        FileWriter write = new FileWriter("Hospital\\Pacientes\\" + ced + ".txt", true);
                        try (PrintWriter print_line = new PrintWriter(write)) {
                            print_line.printf(ced + "\n" + nom + "\n" + sex + "\n" + fec + "\n" + dir + "\n" + pro + "\n" + tel);
                            JOptionPane.showMessageDialog(null, "Paciente registrado exitosamente", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                            jtf_ced.setText("");
                            jtf_nom.setText("");
                            jtf_sex.setText("");
                            jtf_fec.setText("");
                            jtf_dir.setText("");
                            jtf_pro.setText("");
                            jtf_tel.setText("");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(RegistroPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else if (jb_reg.getText().equals("Guardar")) {
                File file = new File("Hospital\\Pacientes\\" + ced + ".txt");
                file.delete();
                try {
                    FileWriter write = new FileWriter("Hospital\\Pacientes\\" + ced + ".txt", true);
                    try (PrintWriter print_line = new PrintWriter(write)) {
                        print_line.printf(ced + "\n" + nom + "\n" + sex + "\n" + fec + "\n" + dir + "\n" + pro + "\n" + tel);
                        jtf_ced.setText("");
                        jtf_nom.setText("");
                        jtf_sex.setText("");
                        jtf_fec.setText("");
                        jtf_dir.setText("");
                        jtf_pro.setText("");
                        jtf_tel.setText("");
                        jtf_bus.setText("");
                        JOptionPane.showMessageDialog(null, "Paciente modifica exitosamente", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(RegistroPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
                jb_reg.setText("Registrar");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR....");
            }
        }
    }//GEN-LAST:event_jb_regActionPerformed

    private void jtf_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_proActionPerformed

    private void jtf_fecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_fecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_fecActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        Hospital principal = new Hospital();

        principal.setTitle("Ventana Principal");

        principal.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jtf_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telActionPerformed

    private void jtf_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_busActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_busActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCedula1;
    private javax.swing.JLabel jLabelDirec;
    private javax.swing.JLabel jLabelFechNacimiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProvin;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTituloPaciente;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton jb_eli;
    private javax.swing.JButton jb_mod;
    public javax.swing.JButton jb_reg;
    private javax.swing.JTextField jtf_bus;
    private javax.swing.JTextField jtf_ced;
    private javax.swing.JTextField jtf_dir;
    private javax.swing.JTextField jtf_fec;
    private javax.swing.JTextField jtf_nom;
    private javax.swing.JTextField jtf_pro;
    private javax.swing.JTextField jtf_sex;
    private javax.swing.JTextField jtf_tel;
    // End of variables declaration//GEN-END:variables
}
