/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Desktop-PC
 */
public class RegistroDoctor extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDoctor
     */
    public RegistroDoctor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloMedico = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelEspecialidad = new javax.swing.JLabel();
        jLabelDirecMedico = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jb_mod = new javax.swing.JButton();
        jb_eli = new javax.swing.JButton();
        jb_reg = new javax.swing.JButton();
        jtf_tel = new javax.swing.JTextField();
        jtf_ced = new javax.swing.JTextField();
        jtf_nom = new javax.swing.JTextField();
        jtf_ape = new javax.swing.JTextField();
        jtf_esp = new javax.swing.JTextField();
        jtf_dir = new javax.swing.JTextField();
        jtf_sal = new javax.swing.JTextField();
        jtf_bus = new javax.swing.JTextField();
        jLabelTelefono1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabelTituloMedico.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabelTituloMedico.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTituloMedico.setText("Medicos");

        jLabelCedula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(153, 153, 153));
        jLabelCedula.setText("Cedula :");

        jLabelNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(153, 153, 153));
        jLabelNombre.setText("Nombre :");

        jLabelApellido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(153, 153, 153));
        jLabelApellido.setText("Apellidos :");

        jLabelEspecialidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelEspecialidad.setForeground(new java.awt.Color(153, 153, 153));
        jLabelEspecialidad.setText("Especialidad :");

        jLabelDirecMedico.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelDirecMedico.setForeground(new java.awt.Color(153, 153, 153));
        jLabelDirecMedico.setText("Direccion :");

        jLabelSalario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSalario.setForeground(new java.awt.Color(153, 153, 153));
        jLabelSalario.setText("Salario :");

        jLabelTelefono.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTelefono.setText("Telefono :");

        jButtonRegresar.setBackground(new java.awt.Color(102, 33, 58));
        jButtonRegresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jb_mod.setBackground(new java.awt.Color(38, 36, 87));
        jb_mod.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jb_mod.setForeground(new java.awt.Color(255, 255, 255));
        jb_mod.setText("Modificar");
        jb_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modActionPerformed(evt);
            }
        });

        jb_eli.setBackground(new java.awt.Color(38, 36, 87));
        jb_eli.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jb_eli.setForeground(new java.awt.Color(255, 255, 255));
        jb_eli.setText("Eliminar");
        jb_eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliActionPerformed(evt);
            }
        });

        jb_reg.setBackground(new java.awt.Color(38, 36, 87));
        jb_reg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jb_reg.setForeground(new java.awt.Color(255, 255, 255));
        jb_reg.setText("Registrar");
        jb_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regActionPerformed(evt);
            }
        });

        jtf_tel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telActionPerformed(evt);
            }
        });

        jtf_ced.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_ced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cedActionPerformed(evt);
            }
        });

        jtf_nom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomActionPerformed(evt);
            }
        });

        jtf_ape.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtf_esp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_espActionPerformed(evt);
            }
        });

        jtf_dir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dirActionPerformed(evt);
            }
        });

        jtf_sal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtf_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_salActionPerformed(evt);
            }
        });

        jtf_bus.setToolTipText("Escriba el ID del Medico");
        jtf_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_busActionPerformed(evt);
            }
        });

        jLabelTelefono1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTelefono1.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTelefono1.setText("Cedula :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelTelefono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jb_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTituloMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRegresar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTelefono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_tel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSalario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_sal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDirecMedico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_dir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelEspecialidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_esp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelApellido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_ape))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_nom))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCedula)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_ced, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloMedico)
                    .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula)
                    .addComponent(jtf_ced, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jtf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(jtf_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspecialidad)
                    .addComponent(jtf_esp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDirecMedico)
                    .addComponent(jtf_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalario)
                    .addComponent(jtf_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jb_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliActionPerformed
        String bus = jtf_bus.getText();
        if (bus.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese cedula del paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            File file = new File("Hospital\\Medicos\\" + bus + ".txt");
            if (file.delete()) {
                JOptionPane.showMessageDialog(null, "Paciente eliminado exitosamente", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Paciente " + bus + " inexistente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        jtf_bus.setText("");

    }//GEN-LAST:event_jb_eliActionPerformed

    private void jb_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modActionPerformed
        String bus = jtf_bus.getText();
        if (bus.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese cedula del paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {            
            File nuevoPaciente = new File("Hospital\\Medicos\\" + bus + ".txt");
            if (nuevoPaciente.exists()) {
                // Asignación de texto al boton registrar->guardar y la casilla de busqueda de cedula a vacio
                jb_reg.setText("Guardar");
                jtf_bus.setText("");
                // Bloqueo de casiilas y botones
                jb_mod.setEnabled(false);
                jb_eli.setEnabled(false);
                jtf_bus.setEnabled(false);
                jtf_ced.setEnabled(false);

                BufferedReader reader;
                try {
                    reader = new BufferedReader(new FileReader("Hospital\\Medicos\\" + bus + ".txt"));
                    String line = reader.readLine();
                    int numLinea = 1;
                    while (line != null) {
                        if (numLinea == 1) {
                            jtf_ced.setText(line);
                        } else if (numLinea == 2) {
                            jtf_nom.setText(line);
                        } else if (numLinea == 3) {
                            jtf_ape.setText(line);
                        } else if (numLinea == 4) {
                            jtf_esp.setText(line);
                        } else if (numLinea == 5) {
                            jtf_dir.setText(line);
                        } else if (numLinea == 6) {
                            jtf_sal.setText(line);
                        } else if (numLinea == 7) {
                            jtf_tel.setText(line);
                        } else {
                            break;
                        }
                        line = reader.readLine();
                        numLinea++;
                    }
                    reader.close();
                } catch (IOException e) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "Paciente " + bus + " inexistente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        jtf_bus.setText("");
    }//GEN-LAST:event_jb_modActionPerformed

    private void jtf_cedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cedActionPerformed

    private void jtf_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telActionPerformed

    private void jtf_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_salActionPerformed

    private void jtf_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dirActionPerformed

    private void jtf_espActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_espActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_espActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        Hospital principal = new Hospital();
        principal.setTitle("Ventana 2");
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jb_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regActionPerformed
        String ced = jtf_ced.getText();
        String nom = jtf_nom.getText();
        String ape = jtf_ape.getText();
        String esp = jtf_esp.getText();
        String dir = jtf_dir.getText();
        String sal = jtf_sal.getText();
        String tel = jtf_tel.getText();

        if (ced.isEmpty() || nom.isEmpty() || ape.isEmpty() || esp.isEmpty() || dir.isEmpty() || sal.isEmpty() || tel.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los espacios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            jb_mod.setEnabled(true);
            jb_eli.setEnabled(true);
            jtf_bus.setEnabled(true);
            jtf_ced.setEnabled(true);
            if (jb_reg.getText().equals("Registrar")) {
                File nuevoMedico = new File("Hospital\\Medicos\\" + ced + ".txt");
                if (nuevoMedico.exists()) {
                    JOptionPane.showMessageDialog(null, "Medico ya registrado", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
                } else {
                    try {
                        FileWriter write = new FileWriter("Hospital\\Medicos\\" + ced + ".txt", true);
                        try (PrintWriter print_line = new PrintWriter(write)) {
                            print_line.printf(ced + "\n" + nom + "\n" + ape + "\n" + esp + "\n" + dir + "\n" + sal + "\n" + tel);
                            JOptionPane.showMessageDialog(null, "Medico registrado exitosamente", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                            jtf_ced.setText("");
                            jtf_nom.setText("");
                            jtf_ape.setText("");
                            jtf_esp.setText("");
                            jtf_dir.setText("");
                            jtf_sal.setText("");
                            jtf_tel.setText("");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(RegistroDoctor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else if (jb_reg.getText().equals("Guardar")) {
                File file = new File("Hospital\\Medicos\\" + ced + ".txt");
                file.delete();
                try {
                    FileWriter write = new FileWriter("Hospital\\Medicos\\" + ced + ".txt", true);
                    try (PrintWriter print_line = new PrintWriter(write)) {
                        print_line.printf(ced + "\n" + nom + "\n" + ape + "\n" + esp + "\n" + dir + "\n" + sal + "\n" + tel);
                        jtf_ced.setText("");
                        jtf_nom.setText("");
                        jtf_ape.setText("");
                        jtf_esp.setText("");
                        jtf_dir.setText("");
                        jtf_sal.setText("");
                        jtf_tel.setText("");
                        jtf_bus.setText("");
                        JOptionPane.showMessageDialog(null, "Medico modifica exitosamente", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(RegistroDoctor.class.getName()).log(Level.SEVERE, null, ex);
                }
                jb_reg.setText("Registrar");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR....");
            }
        }


    }//GEN-LAST:event_jb_regActionPerformed

    private void jtf_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomActionPerformed

    private void jtf_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_busActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_busActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelDirecMedico;
    private javax.swing.JLabel jLabelEspecialidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefono1;
    private javax.swing.JLabel jLabelTituloMedico;
    private javax.swing.JButton jb_eli;
    private javax.swing.JButton jb_mod;
    private javax.swing.JButton jb_reg;
    private javax.swing.JTextField jtf_ape;
    private javax.swing.JTextField jtf_bus;
    private javax.swing.JTextField jtf_ced;
    private javax.swing.JTextField jtf_dir;
    private javax.swing.JTextField jtf_esp;
    private javax.swing.JTextField jtf_nom;
    private javax.swing.JTextField jtf_sal;
    private javax.swing.JTextField jtf_tel;
    // End of variables declaration//GEN-END:variables
}
